Repository dimitri/pgcopydb, pull requests merged in 2023-12, with the labels that each got.

#571 Fix division-by-zero hazard in random_between macro.
  src/bin/pgcopydb/pgsql.c
Labels: bug

#578 Fix application_name truncation notice messages.
  src/bin/pgcopydb/pgsql.c
Labels: bug, enhancement

#579 Fix Postgres connection handling in Large Object related code.
  src/bin/pgcopydb/blobs.c
Labels: bug

#580 Fix interrupt handling in queue_receive.
  src/bin/pgcopydb/queue_utils.c
Labels: enhancement

#569 Use SQLite to store our internal copy of the source catalogs.
  Dockerfile
  docs/design.rst
  src/bin/lib/log/src/log.c
  src/bin/lib/log/src/log.h
  src/bin/pgcopydb/Makefile
  src/bin/pgcopydb/blobs.c
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_compare.c
  src/bin/pgcopydb/cli_copy.c
  src/bin/pgcopydb/cli_dump.c
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_list.h
  src/bin/pgcopydb/cli_restore.c
  src/bin/pgcopydb/cli_snapshot.c
  src/bin/pgcopydb/cli_stream.c
  src/bin/pgcopydb/compare.c
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_paths.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/filtering.c
  src/bin/pgcopydb/filtering.h
  src/bin/pgcopydb/follow.c
  src/bin/pgcopydb/indexes.c
  src/bin/pgcopydb/ld_stream.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/parsing_utils.c
  src/bin/pgcopydb/parsing_utils.h
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/pgcmd.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/progress.h
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/schema.h
  src/bin/pgcopydb/sequences.c
  src/bin/pgcopydb/snapshot.c
  src/bin/pgcopydb/string_utils.c
  src/bin/pgcopydb/summary.c
  src/bin/pgcopydb/summary.h
  src/bin/pgcopydb/table-data.c
  src/bin/pgcopydb/vacuum.c
  tests/.sqliterc
  tests/Dockerfile.pagila
  tests/extensions/copydb.sh
  tests/filtering/copydb.sh
  tests/filtering/exclude.ini
  tests/pagila-multi-steps/copydb.sh
  tests/pagila/copydb.sh
  tests/pagila/docker-compose.yml
  tests/unit/copydb.sh
  tests/unit/expected/3-collations.out
  tests/unit/script/3-collations.sh
  tests/unit/script/4-list-table-split.sh
Labels: enhancement

#584 Use libpq Single Row Mode when fetching catalogs.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/schema.c
Labels: enhancement

#589 Fix crash on exit with --debug and PGCOPYDB_LOG_FILENAME
  src/bin/pgcopydb/main.c
Labels: bug

#595 Fix escaping of identifiers while transforming for wal2json plugin.
  docs/ref/pgcopydb_stream.rst
  src/bin/pgcopydb/cli_stream.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/ld_wal2json.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  tests/Makefile
  tests/cdc-endpos-between-transaction/000000010000000000000002.sql
  tests/cdc-low-level/000000010000000000000002.sql
  tests/cdc-test-decoding/000000010000000000000002.sql
  tests/cdc-wal2json/000000010000000000000002.json
  tests/cdc-wal2json/000000010000000000000002.sql
  tests/cdc-wal2json/Dockerfile
  tests/cdc-wal2json/copydb.sh
  tests/cdc-wal2json/special-ddl.sql
  tests/cdc-wal2json/special-dml.sql
Labels: bug

#597 Review the COPY arguments API to fix TRUNCATE calls.
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/table-data.c
Labels: bug

#598 Fix error handling (--fail-fast) for copy workers.
  docs/design.rst
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/table-data.c
Labels: bug

#599 Skip creating Large Objects workers when database has zero of them.
  src/bin/pgcopydb/blobs.c
  src/bin/pgcopydb/copydb.h
Labels: enhancement

#590 Remove summary files, use our SQLite database instead.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/compare.c
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_paths.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/indexes.c
  src/bin/pgcopydb/lock_utils.c
  src/bin/pgcopydb/lock_utils.h
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/schema.h
  src/bin/pgcopydb/summary.c
  src/bin/pgcopydb/summary.h
  src/bin/pgcopydb/table-data.c
  tests/pagila/copydb.sh
  tests/pagila/docker-compose.yml
Labels: enhancement

#550 Add millisecond level resolution to log lines
  src/bin/lib/log/src/log.c
Labels: enhancement

#600 Mark the Large Objects as done when we found none of them.
  src/bin/pgcopydb/blobs.c
Labels: bug

#603 Fix sub-process "success" condition and error handling.
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/follow.c
  src/bin/pgcopydb/signals.c
  src/bin/pgcopydb/signals.h
Labels: bug, enhancement
