Repository dimitri/pgcopydb, pull requests merged in 2023-11, with the labels that each got.

#525 Remove the usage of txn metadata file
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_transform.c
Labels: bug, enhancement

#521 Update pgcopydb sentinel in the main follow process.
  src/bin/pgcopydb/file_utils.c
  src/bin/pgcopydb/follow.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_replay.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_transform.c
Labels: bug

#528 Improve and fix connection timeout and total retry timeout.
  src/bin/pgcopydb/cli_root.h
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/main.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
Labels: enhancement

#531 Reduce calls to follow_get_sentinel() in the main follow process.
  src/bin/pgcopydb/follow.c
Labels: enhancement
