Repository dimitri/pgcopydb, pull requests merged in 2024-08, with the labels that each got.

#848 Store timelines in internal catalogs
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb_paths.h
  src/bin/pgcopydb/follow.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_stream.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/pgsql_timeline.c
  src/bin/pgcopydb/pgsql_timeline.h
  src/bin/pgcopydb/pgsql_utils.h
Labels: bug, enhancement

#859 Use compose plugin of docker
  tests/blobs/Makefile
  tests/cdc-endpos-between-transaction/Makefile
  tests/cdc-low-level/Makefile
  tests/cdc-test-decoding/Makefile
  tests/cdc-wal2json/Makefile
  tests/endpos-in-multi-wal-txn/Makefile
  tests/extensions/Makefile
  tests/filtering/Makefile
  tests/follow-9.6/Makefile
  tests/follow-9.6/inject.sh
  tests/follow-data-only/Makefile
  tests/follow-data-only/inject.sh
  tests/follow-wal2json/Makefile
  tests/follow-wal2json/inject.sh
  tests/pagila-multi-steps/Makefile
  tests/pagila-standby/Dockerfile
  tests/pagila-standby/Makefile
  tests/pagila/Dockerfile
  tests/pagila/Makefile
  tests/unit/Dockerfile
  tests/unit/Makefile
Labels: Build CI Packaging

#858 Update COPY statistics during the copy operation.
  src/bin/pgcopydb/cli_ping.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/summary.c
  src/bin/pgcopydb/table-data.c
Labels: enhancement

#863 Bugfix: support filtering out only some of the partitions
  src/bin/pgcopydb/schema.c
  tests/filtering/exclude.ini
  tests/filtering/extra.sql
  tests/filtering/include/expected/3-schema-bar-does-not-exists.out
Labels: bug

#857 Use copy with binary.
  docs/include/clone.rst
  docs/include/copy-db.rst
  docs/ref/pgcopydb_clone.rst
  docs/ref/pgcopydb_copy.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/cli_copy.c
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/table-data.c
  tests/endpos-in-multi-wal-txn/copydb.sh
  tests/follow-9.6/copydb.sh
  tests/pagila/copydb.sh
Labels: enhancement

#849 Support timescaledb
  .github/workflows/run-tests.yml
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/extensions.c
  tests/Makefile
  tests/timescaledb/Dockerfile
  tests/timescaledb/Makefile
  tests/timescaledb/compose.yml
  tests/timescaledb/copydb.sh
  tests/timescaledb/fares.sql
  tests/timescaledb/nyc_data_rides.10k.csv
  tests/timescaledb/rides.sql
Labels: enhancement
