Repository dimitri/pgcopydb, pull requests merged in 2024-01, with the labels that each got.

#601 Use our SQLite catalogs for the pgcopydb sentinel table.
  .github/workflows/run-tests.yml
  docs/ref/pgcopydb_stream.rst
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_sentinel.c
  src/bin/pgcopydb/cli_snapshot.c
  src/bin/pgcopydb/cli_stream.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/follow.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_replay.c
  src/bin/pgcopydb/ld_stream.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/lock_utils.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/schema.h
  src/bin/pgcopydb/sentinel.c
  tests/cdc-endpos-between-transaction/000000010000000000000002.json
  tests/cdc-low-level/000000010000000000000002.json
  tests/cdc-test-decoding/000000010000000000000002.json
  tests/cdc-wal2json/000000010000000000000002.json
  tests/follow-9.6/.dockerignore
  tests/follow-9.6/Makefile
  tests/follow-9.6/copydb.sh
  tests/follow-9.6/docker-compose.yml
  tests/follow-9.6/inject.sh
  tests/follow-9.6/workdir/.gitignore
  tests/follow-data-only/.dockerignore
  tests/follow-data-only/Dockerfile.inject
  tests/follow-data-only/Makefile
  tests/follow-data-only/copydb.sh
  tests/follow-data-only/docker-compose.yml
  tests/follow-data-only/inject.sh
  tests/follow-data-only/workdir/.gitignore
  tests/follow-wal2json/.dockerignore
  tests/follow-wal2json/Makefile
  tests/follow-wal2json/docker-compose.yml
  tests/follow-wal2json/inject.sh
  tests/follow-wal2json/workdir/.gitignore
Labels: enhancement

#607 Review CDC/Follow tests workdir cleanup (and git registration).
  tests/follow-9.6/Makefile
  tests/follow-data-only/Makefile
  tests/follow-wal2json/Makefile
Labels: enhancement

#610 Fix pgcopydb list progress command.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/progress.c
Labels: bug

#612 Makefile: Add DEBUG variable to produce debug friendly build.
  src/bin/pgcopydb/Makefile
Labels: enhancement

#617 Fix numerous issues with argument parsing
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_compare.c
  src/bin/pgcopydb/cli_dump.c
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_ping.c
  src/bin/pgcopydb/cli_restore.c
  src/bin/pgcopydb/cli_root.c
  src/bin/pgcopydb/cli_root.h
  src/bin/pgcopydb/cli_sentinel.c
  src/bin/pgcopydb/cli_snapshot.c
  src/bin/pgcopydb/cli_stream.c
  src/bin/pgcopydb/main.c
Labels: enhancement, good first issue

#620 Update actions/checkout version to v4
  .github/workflows/docker-publish.yml
  .github/workflows/run-tests.yml
Labels: Build CI Packaging

#625 Use SQLite for LSN tracking.
  src/bin/pgcopydb/cli_stream.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/lsn_tracking.c
  src/bin/pgcopydb/lsn_tracking.h
  src/bin/pgcopydb/sentinel.c
Labels: enhancement

#626 Fix our exclude-index filtering.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/schema.c
Labels: bug

#629 Fix gcc warnings found when building on i386.
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/filtering.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/schema.c
Labels: Build CI Packaging

#633 Fix large sequence lastValue conversion to 32-bit integer
  src/bin/pgcopydb/catalog.c
Labels: bug

#636 Blind attempt to fix a segfault in copy extensions code.
  src/bin/pgcopydb/cli_copy.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/table-data.c
Labels: bug

#641 Review zero-byte allocation hasards.
  src/bin/pgcopydb/filtering.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/parsing_utils.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/summary.c
Labels: bug

#642 Fix eager extension/collation skipping.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/cli_copy.c
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/schema.c
  tests/unit/setup/14-uuid.sql
  tests/unit/setup/setup.sql
Labels: bug

#648 Fix cache invalidation of zero --split-tables-larger-than setup.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  tests/cdc-wal2json/copydb.sh
Labels: bug

#618 Improve documentation templates
  .github/workflows/run-tests.yml
  .gitignore
  Makefile
  ci/Dockerfile.docs.template
  docs/include/help.rst
  docs/include/stream-cleanup.rst
  docs/include/stream.rst
  docs/ref/pgcopydb.rst
  docs/update-help-messages.sh
  src/bin/pgcopydb/cli_stream.c
Labels: documentation

#647 Use Boehm-Demers-Weiser Garbage Collector.
  Dockerfile
  debian/control
  src/bin/lib/subcommands.c/runprogram.h
  src/bin/pgcopydb/Makefile
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_compare.c
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_restore.c
  src/bin/pgcopydb/cli_sentinel.c
  src/bin/pgcopydb/compare.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/extensions.c
  src/bin/pgcopydb/file_utils.c
  src/bin/pgcopydb/filtering.c
  src/bin/pgcopydb/indexes.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_stream.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_transform.c
  src/bin/pgcopydb/ld_wal2json.c
  src/bin/pgcopydb/lock_utils.c
  src/bin/pgcopydb/lsn_tracking.c
  src/bin/pgcopydb/main.c
  src/bin/pgcopydb/parsing_utils.c
  src/bin/pgcopydb/parsing_utils.h
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/pgcmd.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pidfile.c
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/snapshot.c
  src/bin/pgcopydb/string_utils.c
  src/bin/pgcopydb/string_utils.h
  src/bin/pgcopydb/summary.c
  src/bin/pgcopydb/table-data.c
  tests/Dockerfile.pagila
Labels: bug, enhancement

#654 Fix pgcopydb list progress.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/progress.c
  src/bin/pgcopydb/progress.h
  src/bin/pgcopydb/schema.h
Labels: bug

#658 Fix confusion around reporting operations in progress.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/progress.c
Labels: bug
