Repository dimitri/pgcopydb, pull requests merged in 2024-04, with the labels that each got.

#732 Bump to Postgres 14 to use libpq pipeline mode
  Dockerfile
Labels: Build CI Packaging

#727 Problem: replay_lsn is not moving until the first message received
  src/bin/pgcopydb/ld_stream.c
Labels: bug, enhancement

#735 Dockerfile: make pg_dump more interoperable
  Dockerfile
Labels: Build CI Packaging

#731 Problem: Finding replay_lsn with lsn tracking is 7.5 times slower
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/ld_apply.c
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/lsn_tracking.c
  src/bin/pgcopydb/lsn_tracking.h
Labels: enhancement

#717 Fix cloning with extensions in non default schema
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/schema.h
  tests/pagila/copydb.sh
Labels: bug

#745 Cleanup code removal from previous PR (#717).
  src/bin/pgcopydb/pgcmd.c
Labels: bug, Build CI Packaging

#746 Check that we have TRUNCATE privileges before running the command.
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/table-data.c
Labels: bug, enhancement

#747 Fix varbit parsing in our test_decoding support.
  src/bin/pgcopydb/ld_test_decoding.c
  tests/cdc-test-decoding/000000010000000000000002.json
  tests/cdc-test-decoding/000000010000000000000002.sql
  tests/cdc-test-decoding/ddl.sql
  tests/cdc-test-decoding/dml.sql
Labels: bug, good first issue

#748 Check that a table still exists before running COPY.
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/table-data.c
Labels: enhancement, good first issue

#711 Create extensions in the schema of the original extension
  src/bin/pgcopydb/extensions.c
  tests/extensions/copydb.sh
Labels: bug, enhancement

#752 Fix infinite recursion for schema_list_extensions() catalog query
  src/bin/pgcopydb/schema.c
  tests/extensions/Dockerfile
  tests/extensions/copydb.sh
  tests/extensions/ddl.sql
Labels: bug

#706 fix: use IS NULL during an UPDATE/DELETE
  src/bin/pgcopydb/ld_transform.c
  tests/cdc-wal2json/000000010000000000000002.json
  tests/cdc-wal2json/000000010000000000000002.sql
  tests/cdc-wal2json/ddl.sql
  tests/cdc-wal2json/dml.sql
Labels: bug, good first issue

#762 Fix COPY partitioning.
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/table-data.c
  tests/unit/expected/4-list-table-split.out
Labels: bug

#761 Fix pgsql_escape_identifier memory leak
  src/bin/pgcopydb/ld_stream.h
  src/bin/pgcopydb/ld_test_decoding.c
  src/bin/pgcopydb/ld_wal2json.c
  src/bin/pgcopydb/pgsql.c
Labels: bug

#764 Fix the default value for the table attr list.
  src/bin/pgcopydb/catalog.c
  tests/unit/expected/5-attgenerated.out
  tests/unit/setup/15-attgenerated.sql
  tests/unit/setup/setup.sql
  tests/unit/sql/5-attgenerated.sql
Labels: bug
