Repository dimitri/pgcopydb, pull requests merged in 2024-05, with the labels that each got.

#766 Fix a deadlock situation when queueing a table's indexes.
  src/bin/pgcopydb/indexes.c
Labels: bug

#771 Remove redundant identifier escaping from transform
  src/bin/pgcopydb/ld_transform.c
  tests/cdc-low-level/000000010000000000000002.sql
  tests/cdc-test-decoding/000000010000000000000002.sql
  tests/cdc-test-decoding/continued-txn.sql
Labels: enhancement

#774 Sentinel is updated for every commit
  src/bin/pgcopydb/ld_apply.c
Labels: bug, enhancement

#769 Freeze only if we TRUNCATE
  src/bin/pgcopydb/pgsql.c
Labels: bug, good first issue

#767 Fix SQLite database is locked
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/summary.c
Labels: bug

#779 Implement --skip-db-properties.
  docs/include/clone.rst
  docs/ref/pgcopydb_clone.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/defaults.h
  tests/pagila/copydb.sh
Labels: bug, enhancement, good first issue

#780 Add missing args for skip-db-properties option
  src/bin/pgcopydb/cli_common.c
Labels: bug

#781 Incorrect type used for `partnum` while querying summary table
  src/bin/pgcopydb/summary.c
Labels: bug

#778 Allow identity based sequences to be found and reset
  src/bin/pgcopydb/schema.c
  tests/unit/expected/6-sequences.out
  tests/unit/setup/16-sequences.sql
  tests/unit/setup/setup.sql
  tests/unit/sql/6-sequences.sql
Labels: bug, good first issue

#782 Fix index/constraint lookup when preparing pg_restore list files.
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/summary.c
Labels: bug

#784 BUG: summary_start_timing: db is NULL
  src/bin/pgcopydb/cli_copy.c
Labels: bug

#787 Release v0.16
  CHANGELOG.md
  Dockerfile.debian
  Dockerfile.debian-qa
  GIT-VERSION-GEN
  debian/changelog
  docs/conf.py
  docs/install.rst
  src/bin/pgcopydb/defaults.h
Labels: Build CI Packaging

#788 Post release adjustments
  Dockerfile.debian-qa
  docs/conf.py
Labels: Build CI Packaging

#785 Skip disable by ctid
  docs/include/clone.rst
  docs/include/list-table-parts.rst
  docs/ref/pgcopydb_clone.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_list.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/defaults.h
  tests/unit/expected/4-list-table-split.out
  tests/unit/script/4-list-table-split.sh
  tests/unit/setup/4-list-table-split.sql
Labels: enhancement, good first issue

#789 Allow exclude-index filtering when used with other filters.
  src/bin/pgcopydb/schema.c
  tests/filtering/expected/4-exclude-index.out
  tests/filtering/include.ini
  tests/filtering/sql/4-exclude-index.sql
Labels: bug, enhancement

#790 Optimize extension query
  src/bin/pgcopydb/schema.c
Labels: bug, good first issue

#792 Improve formatting for pretty printed integers
  src/bin/pgcopydb/string_utils.c
Labels: enhancement, good first issue

#793 Introduce new options for estimating table sizes
  README.md
  docs/include/clone.rst
  docs/include/list-table-parts.rst
  docs/include/list-tables.rst
  docs/ref/pgcopydb_clone.rst
  docs/ref/pgcopydb_copy.rst
  docs/ref/pgcopydb_list.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/cli_compare.c
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_list.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/ini_implementation.c
  src/bin/pgcopydb/pg_utils.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/pgcmd.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/schema.h
  src/bin/pgcopydb/string_utils.c
  src/bin/pgcopydb/vacuum.c
  tests/pagila/copydb.sh
  tests/unit/setup/4-list-table-split.sql
Labels: enhancement

#737 Implement support for filtering materialized view and data (refresh).
  docs/ref/pgcopydb_config.rst
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/schema.h
  tests/filtering/Dockerfile
  tests/filtering/copydb.sh
  tests/filtering/exclude.ini
  tests/filtering/exclude/expected/1-ignore-matview.out
  tests/filtering/exclude/sql/1-ignore-matview.sql
  tests/filtering/extra.sql
  tests/filtering/include/expected/1-empty-rental.out
  tests/filtering/include/expected/2-payment-does-not-exists.out
  tests/filtering/include/expected/3-schema-bar-does-not-exists.out
  tests/filtering/include/expected/4-exclude-index.out
  tests/filtering/include/sql/1-empty-rental.sql
  tests/filtering/include/sql/2-payment-does-not-exists.sql
  tests/filtering/include/sql/3-schema-bar-does-not-exists.sql
  tests/filtering/include/sql/4-exclude-index.sql
Labels: enhancement
