Repository dimitri/pgcopydb, pull requests merged in 2024-06, with the labels that each got.

#795 Get the block size from the origin.
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/pgsql.c
  src/bin/pgcopydb/pgsql.h
  src/bin/pgcopydb/schema.c
Labels: enhancement, good first issue

#803 Add support for limiting same table concurrency
  docs/include/clone.rst
  docs/include/list-table-parts.rst
  docs/ref/pgcopydb_clone.rst
  docs/ref/pgcopydb_copy.rst
  src/bin/pgcopydb/catalog.c
  src/bin/pgcopydb/catalog.h
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_list.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/defaults.h
  src/bin/pgcopydb/schema.c
  src/bin/pgcopydb/schema.h
  tests/pagila/docker-compose.yml
  tests/unit/expected/4-list-table-split.out
  tests/unit/script/4-list-table-split.sh
Labels: enhancement

#806 Update versions for checkout github action
  .github/workflows/run-tests.yml
Labels: Build CI Packaging

#804 Use a single dump file to give more dependency information to pg_restore.
  README.md
  docs/include/dump-post-data.rst
  docs/include/dump-pre-data.rst
  docs/include/dump.rst
  docs/include/help.rst
  docs/ref/pgcopydb_clone.rst
  docs/ref/pgcopydb_copy.rst
  docs/ref/pgcopydb_dump.rst
  docs/ref/pgcopydb_restore.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_copy.c
  src/bin/pgcopydb/cli_dump.c
  src/bin/pgcopydb/cli_restore.c
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_paths.h
  src/bin/pgcopydb/dump_restore.c
  src/bin/pgcopydb/pgcmd.c
  src/bin/pgcopydb/pgcmd.h
Labels: bug, enhancement, good first issue

#814 Fix intialisation of the start time, fixing timing reports on subsequent runs
  src/bin/pgcopydb/catalog.c
Labels: bug

#823 Problem: Pipeline sync might deadlock
  src/bin/pgcopydb/pgsql.c
Labels: bug

#807 Refactor environment variable parsing logic
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_compare.c
  src/bin/pgcopydb/cli_list.c
  src/bin/pgcopydb/cli_restore.c
  src/bin/pgcopydb/env_utils.c
  src/bin/pgcopydb/env_utils.h
Labels: enhancement

#825 Introduce --skip-analyze
  docs/include/clone.rst
  docs/ref/pgcopydb_clone.rst
  src/bin/pgcopydb/cli_clone_follow.c
  src/bin/pgcopydb/cli_common.c
  src/bin/pgcopydb/cli_common.h
  src/bin/pgcopydb/copydb.c
  src/bin/pgcopydb/copydb.h
  src/bin/pgcopydb/copydb_schema.c
  src/bin/pgcopydb/defaults.h
Labels: enhancement, good first issue

#830 Fix/build and test
  .github/workflows/run-tests.yml
  Dockerfile
  Makefile
  ci/Dockerfile.docs.template
  ci/check-docs.mk
  src/bin/Makefile
  src/bin/pgcopydb/Makefile
Labels: Build CI Packaging
